### ISSUE TITLE
inconsistent invalid signature

### ISSUE THREAD

**Issue by edcolmar** [ko-redtruck/ln-auth-python#2]
I've been deploying this code to various test domains, and have been having occasional inconsistent signature problems.  Sometimes it works, and other times it does not.  I'm not sure what is going on, but it's unstable enough to prevent me from using lightning login in production.  =(

Test domains:
https://will-test.com
https://unlockd.gg

Source code:
https://github.com/unlockd-gg/backend/tree/main/backend

I also have an open ticket on the getalby plugin.  René Aaron asked me to open after discussing the issue with him.
https://github.com/getAlby/lightning-browser-extension/issues/2667

Any idea what is going on here?

**Comment by ko-redtruck** [comment]
Hi, my code was written as an educational toy project and I strongly recommend against using it in production. In the past I sometimes used this: https://github.com/chill117/lnurl-node But not sure how stable and well maintained it is right now. 

Best of luck to your endeavors :)

**Comment by edcolmar** [comment]
Does not work.  Don't use.  Got it!
